# Cats behaviours

## Samples and behavioural traits
```{r binary, warning=FALSE, echo=FALSE, comments="", message=FALSE}
data <- sample_metadata %>%
  rename(Fear_humans=Acceptance) %>% 
  rename(Unhealthy=Healthy)%>%
  mutate(across(.cols = c(Bites, Hisses, Retreats, Vocalization,Sedating,Dry_skin,Stiff,Agile), ~ case_when(. == "NO" ~ "0",
                                                                              . == "YES" ~ "1",
                                                                              TRUE ~ NA_character_)))%>%
  mutate(across(.cols = c(Fear_humans,Unhealthy), ~ case_when(. == "YES" ~ "0",
                                                              . == "NO" ~ "1",
                                                              TRUE ~ NA_character_)))
```

```{r domestic_design, warning=FALSE, echo=FALSE,comments="", message=FALSE}
design<- data %>% 
  select(sample, Origin)

table<- data %>% 
  select(sample, Bites,Hisses,Retreats,Fear_humans)%>% 
  column_to_rownames(., "sample") %>% 
  mutate_if(is.character,as.numeric)
```

```{r domestic_metadata1, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_domestic <- data %>% 
  filter(Origin=="Tame")

domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

domestic_no$Presence <- 'No'

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11:20))

domestic_yes$Presence <- 'Yes'

Table_domestic <- rbind(domestic_no, domestic_yes)
Table_domestic$Origin <- 'Domestic'
```

```{r feral_metadata1, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <-data %>% 
  filter(Origin=="Feral")

Feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11:20))
Feral_no$Presence <- 'No'

Feral_yes <- colSums(meta_feral ==1, na.rm=TRUE) %>% 
  as.data.frame() %>% 
  rename(Value=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

Feral_yes$Presence <- 'Yes'
Table_feral <- rbind(Feral_no, Feral_yes)
Table_feral$Origin <- 'Feral'

Table_behaviours <- rbind(Table_domestic, Table_feral)
```

```{r plot_metadata_origin, warning=FALSE, echo=FALSE,comments="", message=FALSE}
ggplot(Table_behaviours, aes(x=behaviour, y=Value, fill=Presence)) +
  geom_bar(stat="identity")+
  facet_grid(.~Origin,  scales="free_x")+
  scale_fill_manual(values=c("#088CA2","#823838"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
    strip.background = element_rect(fill = "white"),
    strip.text = element_text(size = 14, lineheight = 0.6),
    strip.placement = "outside",
    panel.background = element_rect(fill = NA, color = "black",linetype = "solid"),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))
    )+
  labs(x = "Behavioural trait", y = "Number of observation")
```
```{r plot_behaviour, warning=FALSE, echo=FALSE,comments="", message=FALSE}
ggplot(Table_behaviours, aes(x=Origin, y=Value, fill=Presence)) +
  geom_bar(stat="identity")+
  facet_wrap( ~ behaviour, strip.position = "top", scales = "free_x", nrow = 1)+
#  stat_compare_means()+
  scale_fill_manual(values=c("#088CA2","#823838"))+
#  facet_grid(.~behaviour,  scales="free_x", strip.position="bottom")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.background = element_rect(fill = "white"),
        strip.text = element_text(size = 9, lineheight = 0.6,angle = 45),
        strip.placement = "outside",
    panel.background = element_rect(fill = NA, color = "black",linetype = "solid"),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    axis.ticks.x = element_blank(),
    )+
  labs(x = "Origin", y = "Number of observation")
```


```{r domestic_metadata_new, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_domestic <- data %>% 
  filter(Origin=="Tame")

domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11:20))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))
domestic_yes$sum <- domestic_yes$Value_yes + domestic_yes$Value_no

domestic_yes <- transform(domestic_yes, Percentage=Value_yes*100/sum)
domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_new, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

feral_yes <- colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11:20))%>%
  right_join(feral_no1, by=join_by(behaviour == behaviour))
feral_yes$sum <- feral_yes$Value_yes + feral_yes1$Value_no

feral_yes <- transform(feral_yes, Percentage=Value_yes*100/sum)

feral_yes$Origin <- 'Feral'

Table_percentages <- rbind(domestic_yes, feral_yes)
```

```{r plot_metadata, warning=FALSE, echo=FALSE,comments="", message=FALSE}
ggplot(Table_percentages, aes(x=Origin, y=Percentage, fill=Origin)) +
  geom_bar(stat="identity")+
  facet_wrap( ~ behaviour, strip.position = "bottom", scales = "free_x", nrow = 1)+
#  stat_compare_means()+
  scale_fill_manual(name="Origin",
          breaks=c("Tame","Feral"),
          values=c("#6A9AC3","#F3B942"))+
#  facet_grid(.~behaviour,  scales="free_x", strip.position="bottom")+
  theme(axis.text.x = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text = element_text(size = 9, lineheight = 0.6,angle = 45),
    strip.placement = "outside",
    panel.background = element_rect(fill = NA, color = "black",linetype = "solid"),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    axis.ticks.x = element_blank(),
    )+
  labs(x = "Behavioural trait", y = "Number of positive observation")
```

***Bites***
```{r domestic_metadata_bites, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_domestic <- data %>% 
  filter(Origin=="Tame")

domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_bites, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Hisses***
```{r domestic_metadata_hisses, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (12))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (12))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_hisses, warning=FALSE, echo=FALSE,comments="", message=FALSE}
feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (12))

#Bites
feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (12)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Retreats***

```{r domestic_metadata_Retreats, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_domestic <- data %>% 
  filter(Origin=="Tame")

domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (13))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (13))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Retreats, warning=FALSE, echo=FALSE,comments="", message=FALSE}
feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (13))

#Bites
feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (13)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Vocalization***

```{r domestic_metadata_Vocalization, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (14))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (14))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Vocalization, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (14))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (14)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Acceptance***

```{r domestic_metadata_Acceptance, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (15))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (15))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Acceptance, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (15))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (15)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Sedating***

```{r domestic_metadata_Sedating, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (16))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (16))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Sedating, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (16))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (16)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Healthy***

```{r domestic_metadata_Healthy, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (17))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (17))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Healthy, warning=FALSE, echo=FALSE,comments="", message=FALSE}
feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (17))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (17)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

***Stiff***

```{r domestic_metadata_Stiff, warning=FALSE, echo=FALSE,comments="", message=FALSE}
domestic_no <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (19))

domestic_yes <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (19))%>%
  right_join(domestic_no, by=join_by(behaviour == behaviour))

domestic_yes$Origin <- 'Tame'
```
```{r feral_metadata_Stiff, warning=FALSE, echo=FALSE,comments="", message=FALSE}
feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (19))

feral_yes <-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (19)) %>%
  right_join(feral_no, by=join_by(behaviour == behaviour))

feral_yes$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes, feral_yes)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```


```{r beha_new, comment="", message=FALSE, warning=FALSE, echo= FALSE,eval=FALSE}
## Selecting social and non-social to humans cats

### 1) Selecting only samples that match the origin and behaviour
sample_tame_behaviour <- rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
  filter(Origin=="Tame")%>% #51tik 10
  filter(frequency==0)%>%
  select(sample)

sample_feral_behaviour <- rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
  filter(Origin=="Feral")%>% #41tik 6
  filter(frequency>0)%>%
  select(sample)

all_samples_behaviour <- rbind(sample_tame_behaviour,sample_feral_behaviour)

sample_metadata_behaviour <- sample_metadata[sample_metadata$sample %in% all_samples_behaviour$sample,]

genome_counts_behaviour <- genome_counts_filt %>%
    dplyr::select(c("genome",sample_metadata_behaviour$sample)) %>%
  filter(rowSums(across(where(is.numeric)))!=0)

genomes <- genome_counts_behaviour$genome 

genome_metadata_behaviour <- genome_metadata %>%
   filter(genome %in% genomes)

genome_tree_behaviour <- keep.tip(genome_tree, tip=genome_metadata_behaviour$genome)
genome_gifts_behaviour <- genome_gifts %>%
  as.data.frame() %>% 
  rownames_to_column(., "genome") %>%
  filter(genome %in% genomes)%>% 
  column_to_rownames(., "genome")
```

```{r beha_group, comment="", message=FALSE, warning=FALSE, echo= FALSE,eval=FALSE}
### 2) Grouping according to the behaviour

sample_metadata_behaviour <- rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
 # filter(Origin=="Tame")%>% #51tik 10
      mutate(behaviour = case_when(frequency==0~"social",
                                     frequency>0~"antisocial"
                                     )) %>% 
  select(sample, behaviour) %>% 
  right_join(sample_metadata, by=join_by(sample == sample))%>%
    mutate(across(.cols = c(Origin), ~ case_when(. == "Tame" ~ "domestic",
                                                              . == "Feral" ~ "feral",
                                                              TRUE ~ NA_character_))) %>%
  rename(Sex=F.M)%>%
  rename(Behaviour=behaviour)

write_tsv(sample_metadata_behaviour, "data/sample_metadata_behaviour.tsv")

new_behaviours <- rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
 # filter(Origin=="Tame")%>% #51tik 10
      mutate(behaviour = case_when(frequency==0~"Tame",
                                     frequency>0~"Feral"
                                     )) %>% 
  select(sample, behaviour) %>% 
  right_join(sample_metadata, by=join_by(sample == sample))%>%
    group_by(behaviour) %>%
    summarise(count=n())

# Only those that match origin with behaviour
sample_metadata_behaviour%>%
    group_by(Location, Origin) %>%
    summarise(count=n())
# New behavioural classification
new_behaviours%>%
    group_by(behaviour) %>%
    summarise(count=n())

# Original behavioural classification
sample_metadata%>%
    group_by(Location, Origin) %>%
    summarise(count=n())

new_behaviours$similarity <- new_behaviours$behaviour == new_behaviours$Origin
new_behaviours%>%
    group_by(Location, similarity) %>%
    summarise(count=n())
new_behaviours%>%
    group_by(similarity, Origin) %>%
    summarise(count=n())
```




```{r beta_div_beha, comment="", message=FALSE, warning=FALSE, echo= FALSE,eval=FALSE}
beta_q0n_behaviour <- genome_counts_behaviour %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  dplyr::select_if(~!all(. == 0)) %>%
  hillpair(., q = 0)

beta_q1n_behaviour <- genome_counts_behaviour %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  dplyr::select_if(~!all(. == 0)) %>%
  hillpair(., q = 1)

beta_q1p_behaviour <- genome_counts_behaviour %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  dplyr::select_if(~!all(. == 0)) %>%
  hillpair(., q = 1, tree = genome_tree)

beta_q1f_behaviour <- genome_counts_behaviour %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  dplyr::select_if(~!all(. == 0)) %>%
  hillpair(., q = 1, dist = dist)
```

```{r behapermanova, comment="", message=FALSE, warning=FALSE, echo= FALSE,eval=FALSE}
save(beta_q0n_behaviour, 
     beta_q1n_behaviour, 
     beta_q1p_behaviour, 
     beta_q1f_behaviour, 
     file = "data/beta_behaviour.Rdata")
```



```{r permanova, comment="", message=FALSE, warning=FALSE, echo= FALSE,eval=FALSE}
## Permanova
#Richness
betadisper(beta_q0n_behaviour$C, sample_metadata_behaviour$Origin) %>% permutest(., pairwise = TRUE) 
adonis2(beta_q0n_behaviour$C ~ Origin, 
        data = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q0n_behaviour$C))), 
        permutations = 999, 
        strata = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q0n_behaviour$C))) %>% pull(Location)) %>%
        broom::tidy() %>%
        tt()

#Neutral diversity
betadisper(beta_q1n$C, sample_metadata_behaviour$Origin) %>% permutest(., pairwise = TRUE) 
adonis2(beta_q1n$C ~ Origin, 
        data = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1n$C))), 
        permutations = 999, 
        strata = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1n$C))) %>% pull(Location)) %>%
        broom::tidy() %>%
        tt()

#Phylogenetic diversity
betadisper(beta_q1p$C, sample_metadata_behaviour$Origin) %>% permutest(., pairwise = TRUE) 
adonis2(beta_q1p$C ~ Origin, 
        data = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1p$C))), 
        permutations = 999, 
        strata = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1p$C))) %>% pull(Location)) %>%
        broom::tidy() %>%
        tt()

#Functional diversity
betadisper(beta_q1f$C, sample_metadata_behaviour$Origin) %>% permutest(., pairwise = TRUE) 
adonis2(beta_q1f$C ~ Origin, 
        data = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1f$C))), 
        permutations = 999, 
        strata = sample_metadata_behaviour %>% arrange(match(sample,labels(beta_q1f$C))) %>% pull(Location)) %>%
        broom::tidy() %>%
        tt()
```


