# Virulence factor analysis

```{r load_data_virulence}
load("data/data.Rdata")
virulence_summary <- read_tsv("data/virulence_summary.tsv") %>%
    rename(genome=1)%>%
    arrange(match(genome,genome_metadata$genome))%>% 
  column_to_rownames(., "genome")
```

# AVI value

```{r}
genome_counts_rel <- genome_counts %>%
  mutate_at(vars(-genome),~./sum(.))%>% 
  column_to_rownames(., "genome")

result_AVI <- data.frame(matrix(ncol = ncol(genome_counts_rel), nrow = nrow(genome_counts_rel)))
colnames(result_AVI) <- colnames(genome_counts_rel)
rownames(result_AVI) <- rownames(genome_counts_rel)

for (i in 1:nrow(virulence_summary)) {
  # Multiply the ith row of df2 by the ith cell of the first column of df1
  result_AVI[i, ] <- genome_counts_rel[i, ] * virulence_summary[i, 6]
}
```

## Mean AVI values
```{r}
result_AVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(AVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample))%>%
  group_by(location, origin) %>%
  summarise(average=mean(AVI))
```

## Plots
```{r}
result_AVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(AVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = AVI, x = location, group=location, color=location, fill=location)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(alpha=0.5) +
  scale_color_manual(values = location_colors) +
  scale_fill_manual(values = str_c(location_colors, "50")) +
  facet_wrap(. ~ origin, scales = "free", ncol=4) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12))+
    guides(fill = guide_legend(override.aes = list(size=3)))
```

```{r}
result_AVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(AVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = AVI, x = origin, group=origin, color=origin, fill=origin)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(alpha=0.5) +
  scale_color_manual(values = origin_colors) +
  scale_fill_manual(values = str_c(origin_colors, "50")) +
  facet_wrap(. ~ location, scales = "free", ncol=4) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12))+
    guides(fill = guide_legend(override.aes = list(size=3)))
```
```{r}
result_AVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(AVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = AVI, x = origin, group=origin, color=origin, fill=origin)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, width=0.4) +
  geom_jitter(alpha=0.5, width=0.2, show.legend = FALSE) +
  scale_color_manual(values = origin_colors) +
  scale_fill_manual(values = str_c(origin_colors, "50")) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())+
    guides(fill = guide_legend(override.aes = list(size=3)))
```

# NVI value

```{r}
genome_counts_rel <- genome_counts %>%
  mutate_at(vars(-genome),~./sum(.))%>% 
  column_to_rownames(., "genome")

result_NVI <- data.frame(matrix(ncol = ncol(genome_counts_rel), nrow = nrow(genome_counts_rel)))
colnames(result_NVI) <- colnames(genome_counts_rel)
rownames(result_NVI) <- rownames(genome_counts_rel)

for (i in 1:nrow(virulence_summary)) {
  # Multiply the ith row of df2 by the ith cell of the first column of df1
  result_NVI[i, ] <- genome_counts_rel[i, ] * virulence_summary[i, 7]
}
```

## Mean NVI values
```{r}
result_NVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(NVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample))%>%
  group_by(location, origin) %>%
  summarise(average=mean(NVI))
```

## Plots
```{r}
result_NVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(NVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = NVI, x = location, group=location, color=location, fill=location)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(alpha=0.5) +
  scale_color_manual(values = location_colors) +
  scale_fill_manual(values = str_c(location_colors, "50")) +
  facet_wrap(. ~ origin, scales = "free", ncol=4) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12))+
    guides(fill = guide_legend(override.aes = list(size=3)))
```

```{r}
result_NVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(NVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = NVI, x = origin, group=origin, color=origin, fill=origin)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(alpha=0.5) +
  scale_color_manual(values = origin_colors) +
  scale_fill_manual(values = str_c(origin_colors, "50")) +
  facet_wrap(. ~ location, scales = "free", ncol=4) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12))+
    guides(fill = guide_legend(override.aes = list(size=3)))
```
```{r}
result_NVI %>%
  colSums() %>% 
  as.data.frame() %>% 
  rename(NVI=".") %>%
  rownames_to_column(., "sample") %>% 
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = NVI, x = origin, group=origin, color=origin, fill=origin)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, width=0.4) +
  geom_jitter(alpha=0.5, width=0.2, show.legend = FALSE) +
  scale_color_manual(values = origin_colors) +
  scale_fill_manual(values = str_c(origin_colors, "50")) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 12, color="black",face="bold"),
        strip.background = element_blank(),
        panel.grid.minor.x = element_line(size = .1, color = "grey"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())+
    guides(fill = guide_legend(override.aes = list(size=3)))
```
