# Differential abundace analysis by location

## Ancombc2 (considering structural zeros)
```{r ancom_rand, comment="", echo=FALSE, message=FALSE, warning=FALSE}
library(ANCOMBC)
set.seed(1234) #set seed for reproducibility
ancom_rand_output_family = ancombc2(data = physeq_genome, 
                  assay_name = "counts",
                  tax_level = "family", #change to agglomerate analysis to a higher taxonomic range
                  fix_formula = "Location", #fixed variable(s)
#                  rand_formula = "(1|Individual)",
                  p_adj_method = "holm", 
                  pseudo_sens = TRUE,
                  prv_cut = 0.10, 
                  s0_perc = 0.05,
                  group = "Location", 
                  struc_zero = TRUE, 
                  neg_lb = FALSE,
                  alpha = 0.05, 
                  n_cl = 2, 
                  verbose = TRUE,
                  global = TRUE, 
                  pairwise = TRUE, 
                  dunnet = TRUE, 
                  trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = NULL,
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)
ancom_rand_output$res_pair %>%
    dplyr::filter(diff_LocationCaboVerde == 1 |
                      diff_LocationDenmark == 1 | 
                      diff_LocationMalaysia == 1)
tax <- data.frame(physeq_genome_filtered@tax_table) %>%
  rownames_to_column(., "taxon")

ancombc_rand_table <- ancom_rand_output$res %>%
  dplyr::select(taxon, lfc_regionIttoqqortoormiit, p_regionIttoqqortoormiit) %>%
  filter(p_regionIttoqqortoormiit < 0.05) %>%
  dplyr::arrange(p_regionIttoqqortoormiit) %>%
  merge(., tax, by="taxon")

colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
#  mutate_at(vars(phylum), ~ str_replace(., "[dpcofgs]__", ""))  %>%
  right_join(tax, by=join_by(phylum == phylum)) %>%
  dplyr::select(phylum, colors) %>%
  mutate(colors = str_c(colors, "80"))  %>% #add 80% alpha
	unique() %>%
	dplyr::arrange(phylum)

tax_table <- as.data.frame(unique(ancombc_rand_table$phylum))
colnames(tax_table)[1] <- "phylum"
tax_color <- merge(tax_table, colors_alphabetic, by="phylum")%>%
	dplyr::arrange(phylum) %>%
	dplyr::select(colors) %>%
	pull()
```

```{r ancombc_rand_plot, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
res_pair = ancom_rand_output_family$res_pair

df_fig_pair1 = res_pair %>%
    dplyr::filter(diff_LocationBrazil == 1 |
                      diff_LocationSpain == 1 | 
                      diff_LocationSpain_LocationBrazil == 1) %>%
    dplyr::mutate(lfc1 = ifelse(diff_LocationBrazil == 1, 
                                round(lfc_LocationBrazil, 2), 0),
                  lfc2 = ifelse(diff_LocationSpain == 1, 
                                round(lfc_LocationSpain, 2), 0),
                  lfc3 = ifelse(diff_LocationSpain_LocationBrazil == 1, 
                                round(lfc_LocationSpain_LocationBrazil, 2), 0)) %>%
    tidyr::pivot_longer(cols = lfc1:lfc3, 
                        names_to = "group", values_to = "value") %>%
    dplyr::arrange(taxon)

df_fig_pair2 = res_pair %>%
    dplyr::filter(diff_LocationBrazil == 1 |
                      diff_LocationCaboVerde == 1 | 
                      diff_LocationCaboVerde_LocationBrazil == 1) %>%
    dplyr::mutate(lfc1 = ifelse(passed_ss_LocationBrazil == 1 & diff_LocationBrazil == 1, 
                                "aquamarine3", "black"),
                  lfc2 = ifelse(passed_ss_LocationSpain == 1 & diff_LocationSpain == 1, 
                                "aquamarine3", "black"),
                  lfc3 = ifelse(passed_ss_LocationSpain_LocationBrazil == 1 & diff_LocationSpain_LocationBrazil == 1, 
                                "aquamarine3", "black")) %>%
    tidyr::pivot_longer(cols = lfc1:lfc3, 
                        names_to = "group", values_to = "color") %>%
    dplyr::arrange(taxon)

df_fig_pair = df_fig_pair1 %>%
    dplyr::left_join(df_fig_pair2, by = c("taxon", "group"))

df_fig_pair$group = recode(df_fig_pair$group, 
                          `lfc1` = "Brazil - Aruba",
                          `lfc2` = "Spain - Aruba",
                          `lfc3` = "Spain - Brazil")

df_fig_pair$group = factor(df_fig_pair$group, 
                          levels = c("Brazil - Aruba",
                                     "Spain - Aruba", 
                                     "Spain - Brazil"))

lo = floor(min(df_fig_pair$value))
up = ceiling(max(df_fig_pair$value))
mid = (lo + up)/2
fig_pair = df_fig_pair %>%
    ggplot(aes(x = group, y = taxon, fill = value)) + 
    geom_tile(color = "black") +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         na.value = "white", midpoint = mid, limit = c(lo, up),
                         name = NULL) +
    geom_text(aes(group, taxon, label = value, color = color), size = 4) +
    scale_color_identity(guide = FALSE) +
    labs(x = NULL, y = NULL, title = "Log fold changes") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
fig_pair
```
## Ancombc2: sex
```{r ancom_rand, comment="", echo=FALSE, message=FALSE, warning=FALSE}
physeq_genome
set.seed(1234) #set seed for reproducibility
ancom_rand_output_sex = ancombc2(data = physeq_genome, 
                  assay_name = "counts",
                  tax_level = NULL, #change to agglomerate analysis to a higher taxonomic range
                  fix_formula = "F.M", #fixed variable(s)
                  rand_formula = "(1|Location)",
                  p_adj_method = "holm", 
                  pseudo_sens = TRUE,
                  prv_cut = 0.10, 
                  s0_perc = 0.05,
                  group = "Location", 
                  struc_zero = TRUE, 
                  neg_lb = FALSE,
                  alpha = 0.05, 
                  n_cl = 2, 
                  verbose = TRUE,
                  global = FALSE, 
                  pairwise = FALSE, 
                  dunnet = FALSE, 
                  trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
#                  lme_control = NULL,
                  lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)

```
```{r}
taxonomy <- data.frame(physeq_genome@tax_table) %>%
  rownames_to_column(., "taxon") %>%
  mutate_at(vars(phylum, genus), ~ str_replace(., "[dpcofgs]__", ""))

ancombc_rand_table_mag <- ancom_rand_output_sex$res %>%
  dplyr::select(taxon, lfc_F.MMale, p_F.MMale) %>%
  filter(p_F.MMale < 0.05) %>%
  dplyr::arrange(p_F.MMale) %>%
  merge(., taxonomy, by="taxon") %>%
  mutate_at(vars(phylum, genus), ~ str_replace(., "[dpcofgs]__", ""))%>%
  dplyr::arrange(lfc_F.MMale)
  
colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  mutate_at(vars(phylum), ~ str_replace(., "[dpcofgs]__", ""))  %>%
  right_join(taxonomy, by=join_by(phylum == phylum)) %>%
  dplyr::select(phylum, colors) %>%
  mutate(colors = str_c(colors, "80"))  %>% #add 80% alpha
	unique() %>%
	dplyr::arrange(phylum)

tax_table <- as.data.frame(unique(ancombc_rand_table_mag$phylum))
  
  
colnames(tax_table)[1] <- "phylum"
tax_color <- merge(tax_table, colors_alphabetic, by="phylum")%>%
	dplyr::arrange(phylum) %>%
	dplyr::select(colors) %>%
	pull()
```


```{r ancombc_rand_plot, comment="", echo=FALSE, message=FALSE, warning=FALSE}
#pdf("figures/different_mag_StrucZero_new.pdf",width=10, height=8)
ancombc_rand_table_mag%>%
      mutate(genus=factor(genus,levels=ancombc_rand_table_mag$genus)) %>%
ggplot(., aes(x=lfc_F.MMale, y=forcats::fct_rev(genus), fill=phylum)) + #forcats::fct_rev()
  geom_col() + 
  scale_fill_manual(values=tax_color) + 
  geom_hline(yintercept=0) + 
#  coord_flip()+
  theme(panel.background = element_blank(),
        axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14, face = "bold"),
        legend.position = "right", legend.box = "vertical")+
  xlab("log2FoldChange") + 
  ylab("Species")+
  guides(fill=guide_legend(title="Phylum"))
#dev.off()
```
