```{r domestic_metadata, warning=FALSE, echo=FALSE,comments="", message=FALSE}
design<- data %>% 
  select(sample, Origin)
table<- data %>% 
  select(sample, Bites,Hisses,Retreats,Acceptance)%>% 
  column_to_rownames(., "sample") %>% 
  mutate_if(is.character,as.numeric)

rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
  filter(Origin=="Tame")#51tik 10

rowSums(table, na.rm = TRUE)%>%
  as.data.frame() %>% 
  rename(frequency=".")%>% 
  rownames_to_column("sample") %>% 
  right_join(design, by=join_by(sample == sample)) %>%
  filter(Origin=="Feral")#41tik 6



rda.model <- rda(table ~ Origin, data = design)# Run the model

# Anova
anova(rda.model)
# anova(hel_rda,by="axis")
# summary(hel_rda)
RsquareAdj(rda.model)

# Prepare data for plotting
rda_sc_wa <- vegan::scores(rda.model,
  display = "wa",
  scaling = 1
)
rda_sc_cn <- data.frame(vegan::scores(rda.model,
  display = "cn",
  scaling = 1
))
rda_sc_sp <- data.frame(vegan::scores(rda.model,
  display = "sp",
  scaling = 2
))

# Select MAGs from quantile
ASV_Scores_RDA1quantiles <- quantile(rda_sc_sp$RDA1,
  probs = c(0.01, 0.99)
)
HighFit_ASVs <- rda_sc_sp[
  rda_sc_sp$RDA1 < ASV_Scores_RDA1quantiles[1] |
    rda_sc_sp$RDA1 > ASV_Scores_RDA1quantiles[2],
]

HighFit_ASVNames <- rownames(HighFit_ASVs)
species_index <- data.frame(
  Species = HighFit_ASVNames,
  Index = 1:length(HighFit_ASVNames)
)

# combine dataframes
all_dataframe <- data.frame(rda_sc_wa, design)
```
```{r}
# Plot
ggplot(all_dataframe, aes(y = PC1, x = RDA1)) +
  geom_point(aes(y = PC1, x = RDA1, colour = Origin)) +
  # text
  xlab("RDA1 (%)") +
  ylab("PC1 (%)") +
#  ggtitle("Caecum microbiome development (AdjR2 = 0.20)") +
  # segment
geom_segment(data = HighFit_ASVs,
             aes(x = 0, xend = RDA1, y = 0, yend = PC1),
             arrow = arrow(length = unit(0.25, "cm")),
             color = "grey") +
geom_point(data = HighFit_ASVs,
            aes(y = PC1, x = RDA1),
            show.legend = FALSE,
            color = "grey") +
geom_label_repel(data = HighFit_ASVs,
                  aes(y = PC1, x = RDA1,label = species_index$Species),
                  size = 3,
                  show.legend = FALSE,
                  colour = "grey",
                  max.overlaps = 20) +
  scale_colour_manual(values = c("red", "blue")) +
  scale_shape_discrete(solid = TRUE) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 10),
    legend.position = "none"
  )

```










```{r feral_metadata, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

feral_yes <- colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11:20))%>%
  right_join(feral_no1, by=join_by(behaviour == behaviour))
feral_yes$sum <- feral_yes$Value_yes + feral_yes1$Value_no

feral_yes <- transform(feral_yes, Percentage=Value_yes*100/sum)

feral_yes$Origin <- 'Feral'

Table_percentages <- rbind(domestic_yes, feral_yes)
```



```{r domestic_metadata, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_domestic <- data %>% 
  filter(Origin=="Tame")

domestic_no1 <- colSums(meta_domestic ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11:20))

domestic_yes1 <- colSums(meta_domestic ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11))%>%
  right_join(domestic_no1, by=join_by(behaviour == behaviour))

domestic_yes1$Origin <- 'Tame'
```
```{r feral_metadata, warning=FALSE, echo=FALSE,comments="", message=FALSE}
meta_feral <- data %>% 
  filter(Origin=="Feral")

feral_no1 <- colSums(meta_feral ==0, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_no=".")%>% 
  rownames_to_column("behaviour")%>%
  slice(., (11))

#Bites
feral_yes1<-colSums(meta_feral ==1, na.rm=TRUE)%>% 
  as.data.frame() %>% 
  rename(Value_yes=".")%>% 
  rownames_to_column("behaviour") %>%
  slice(., (11)) %>%
  right_join(feral_no1, by=join_by(behaviour == behaviour))

feral_yes1$Origin <- 'Feral'
  
Table_percentages <- rbind(domestic_yes1, feral_yes1)%>%
  select(-behaviour)%>%
  column_to_rownames(., "Origin")
  
chisq.test(Table_percentages)
```

```{r}
Table_percentages %>%
  slice(., (1,11))%>% 
  t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame()%>% 
  mutate_if(is.character,as.numeric)

test<- Table_percentages %>% 
  column_to_rownames(., "behaviour")
  chisq.test(Table_percentages)
  
  
  %>%
  select(Origin,Bites,Hisses)%>%
  rownames_to_column(., "nothing")%>% 
  column_to_rownames(., "Origin")
 #   pivot_longer(-c(sample,region), names_to = "Phylum", values_to = "value") %>%
    group_by(behaviour) %>%
    summarise(p_value = wilcox.test(Value_no ~ Origin)$p.value) %>%
    mutate(p_adjust=p.adjust(p_value, method="BH")) %>%
    filter(p_adjust < 0.05)

Modelq0_all <- MASS::glm.nb(Percentage ~ Bites+Hisses+Retreats+Vocalization+Acceptance+Sedating+Healthy+Dry_skin+Stiff+Agile, data = Table_percentages,trace=TRUE)

```
